options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Build
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-f","workers/worker1/Dockerfile",
      "-t","us-central1-docker.pkg.dev/$PROJECT_ID/workers/gpu-worker:worker1-$COMMIT_SHA",
      "workers/worker1"
    ]

# 2️⃣ Authenticate Docker with Artifact Registry (CRITICAL)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "auth",
      "configure-docker",
      "us-central1-docker.pkg.dev",
      "--quiet"
    ]

# 3️⃣ Push
- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/workers/gpu-worker:worker1-$COMMIT_SHA"
    ]

# 4️⃣ Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run","deploy","worker1",
      "--image","us-central1-docker.pkg.dev/$PROJECT_ID/workers/gpu-worker:worker1-$COMMIT_SHA",
      "--region","us-central1",
      "--concurrency","1",
      "--max-instances","2",
      "--no-allow-unauthenticated",
      "--set-env-vars","WORKER_ID=worker1,WORKER_TYPE=realtime,GPU=L4"
    ]
