options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build + Auth + Push (same container)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      docker build -f workers/worker1/Dockerfile \
        -t us-central1-docker.pkg.dev/$PROJECT_ID/workers/worker1:$COMMIT_SHA \
        workers/worker1
      docker push us-central1-docker.pkg.dev/$PROJECT_ID/workers/worker1:$COMMIT_SHA

# Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "run","deploy","worker1",
      "--image","us-central1-docker.pkg.dev/$PROJECT_ID/workers/worker1:$COMMIT_SHA",
      "--region","us-central1",
      "--concurrency","1",
      "--max-instances","2",
      "--no-allow-unauthenticated",
      "--set-env-vars","WORKER_ID=worker1,WORKER_TYPE=realtime,GPU=L4"
    ]
